env:
  global:
    - GIT_NAME: "'Nano Development'"
    - GIT_EMAIL: development@nano.org
    - GH_REF: git@github.com:nanocurrency/nano-docs.git
language: python
python:
  - "3.5"
before_script:
  - pip install mkdocs
  - pip install pymdown-extensions
  - pip install mkdocs-material
  - pip install MarkdownHighlight
  - pip install mkdocs-redirects
script:
  - |
    if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
      mkdocs build --strict
    elif [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
      openssl aes-256-cbc -K $encrypted_5f828affe522_key -iv $encrypted_5f828affe522_iv -in deploy-key.enc -out deploy-key -d
      chmod 600 deploy-key
      eval `ssh-agent -s`
      ssh-add deploy-key
      git config user.name "Nano Development"
      git config user.email "development@nano.org"
      git remote add gh-token "${GH_REF}"
      git fetch gh-token
      git fetch gh-token gh-pages:gh-pages
      PYTHONPATH=src/ mkdocs gh-deploy -v --clean --remote-name gh-token
      git push gh-token gh-pages
    fi