name: nano-docs-build
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac90
      - uses: actions/setup-python@41b7212
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: pip install mkdocs-material
      - run: mkdocs build --strict

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
