name: build
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 #v3.1.0
      - uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 #v4.3.0
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: mkdocs build --strict

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
