name: publish-docker-pr
on: pull_request

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  build_publish:
    runs-on: ubuntu-latest
    env:
      PRODUCTION: TRUE
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 #v3.1.0

      # Build and test Docker image
      - run: |
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u nanocurrency --password-stdin
          docker pull squidfunk/mkdocs-material:9.4.10@sha256:01605a03397a654b74b9de3157f56915d1e075e2d3bd22fcf3fb82c443553c25
          docker build -t ghcr.io/nanocurrency/nano-docs:pr-${{ env.PR_NUMBER }} .
          docker push ghcr.io/nanocurrency/nano-docs:pr-${{ env.PR_NUMBER }}
